<script setup lang="ts">
import { computed, nextTick, ref, watch } from 'vue';
import { FormField } from '@jumpcloud/circuit/components';
import InputText from 'primevue/inputtext';
import Divider from 'primevue/divider';
import Select from 'primevue/select';
import SelectButton from 'primevue/selectbutton';
import { CommandLineIcon, MagnifyingGlassIcon } from '@heroicons/vue/24/outline';
import Phase01OauthAdvancedCollapse from './Phase01OauthAdvancedCollapse.vue';
import type { Phase01ServerFormState } from '../shared/types';
import { generatePrefixFromName } from '../shared/prefixFromName';

function isValidHttpOrHttpsUrl(value: string): boolean {
  const t = value.trim();
  if (!t) return false;
  try {
    const u = new URL(t);
    return u.protocol === 'http:' || u.protocol === 'https:';
  } catch {
    return false;
  }
}

const addServerEmptyIllustrationSrc = new URL(
  './assets/add-server-empty-illustration.png',
  import.meta.url,
).href;

interface SsoApp {
  id: string;
  name: string;
  domain: string;
  description: string;
  mcpDocsUrl: string;
}

const props = defineProps<{
  /** When true, dialog is open — used to reset picker / advanced panel state */
  active: boolean;
  mode: 'add' | 'edit';
  editingServerSlug?: string;
  editingServerName?: string;
  serverForm: Phase01ServerFormState;
  authStyleOptions: { label: string; value: string }[];
  /**
   * Add mode only. When the dialog opens, restores picker state (e.g. Storybook states).
   * `initial` / omit — empty selection. `custom` — custom app flow. A string — catalog `id` from the SSO list.
   */
  addFlowPreset?: 'initial' | 'custom' | string;
  /** When `addFlowPreset` is a catalog app id, optional MCP URL applied after selection (demos). */
  addFlowSeedMcpUrl?: string;
}>();

const jumpCloudSsoHref = 'https://jumpcloud.com/solutions/single-sign-on';

const ssoApps: SsoApp[] = [
  { id: 'github', name: 'GitHub', domain: 'github.com', description: 'Access repositories, issues, pull requests, and code search via GitHub\'s MCP integration.', mcpDocsUrl: 'https://github.com/github/github-mcp-server' },
  { id: 'slack', name: 'Slack', domain: 'slack.com', description: 'Send messages, manage channels, and search conversations through Slack\'s MCP server.', mcpDocsUrl: 'https://api.slack.com/docs/mcp' },
  { id: 'notion', name: 'Notion', domain: 'notion.so', description: 'Query and update Notion pages, databases, and workspaces via the MCP protocol.', mcpDocsUrl: 'https://developers.notion.com/docs/mcp' },
  { id: 'figma', name: 'Figma', domain: 'figma.com', description: 'Inspect designs, extract tokens, and read component data from Figma files.', mcpDocsUrl: 'https://www.figma.com/developers/mcp' },
  { id: 'stripe', name: 'Stripe', domain: 'stripe.com', description: 'Manage payments, subscriptions, and customer data through Stripe\'s MCP server.', mcpDocsUrl: 'https://docs.stripe.com/mcp' },
  { id: 'salesforce', name: 'Salesforce', domain: 'salesforce.com', description: 'Access CRM records, reports, and automation workflows via Salesforce MCP.', mcpDocsUrl: 'https://developer.salesforce.com/docs/mcp' },
  { id: 'jira', name: 'Jira', domain: 'atlassian.com', description: 'Create and manage issues, sprints, and project boards through Jira\'s MCP integration.', mcpDocsUrl: 'https://developer.atlassian.com/cloud/jira/mcp' },
  { id: 'linear', name: 'Linear', domain: 'linear.app', description: 'Track issues, cycles, and projects using Linear\'s MCP server.', mcpDocsUrl: 'https://linear.app/docs/mcp' },
  { id: 'sentry', name: 'Sentry', domain: 'sentry.io', description: 'Monitor errors, performance issues, and release health via Sentry MCP.', mcpDocsUrl: 'https://docs.sentry.io/mcp' },
  { id: 'asana', name: 'Asana', domain: 'asana.com', description: 'Manage tasks, projects, and team workloads through Asana\'s MCP server.', mcpDocsUrl: 'https://developers.asana.com/docs/mcp' },
  { id: 'datadog', name: 'Datadog', domain: 'datadoghq.com', description: 'Query metrics, logs, and monitors via Datadog\'s MCP integration.', mcpDocsUrl: 'https://docs.datadoghq.com/mcp' },
  { id: 'confluence', name: 'Confluence', domain: 'atlassian.com', description: 'Search and manage wiki pages, spaces, and documentation through Confluence MCP.', mcpDocsUrl: 'https://developer.atlassian.com/cloud/confluence/mcp' },
];

const selectedApp = ref<string | null>(null);
const isCustomMode = ref(false);
const lastAutoGeneratedPrefix = ref('');

const appSelectRef = ref();

const oauthAdvancedCollapsed = ref(true);

/** Set after URL field loses focus when empty or not a valid http(s) URL; cleared on input or dialog open. */
const urlBlurErrorMessage = ref<string | null>(null);

const URL_EMPTY_MSG = 'Enter a URL.';
const URL_INVALID_MSG = 'Enter a valid URL starting with http:// or https://.';

watch(
  () => props.serverForm.url,
  () => {
    urlBlurErrorMessage.value = null;
  },
);

watch(
  () => props.active,
  (open) => {
    if (open) {
      oauthAdvancedCollapsed.value = true;
      urlBlurErrorMessage.value = null;
    }
    if (open && props.mode === 'add') {
      lastAutoGeneratedPrefix.value = '';
      const preset = props.addFlowPreset ?? 'initial';
      if (preset === 'custom') {
        selectedApp.value = null;
        isCustomMode.value = true;
      } else if (preset !== 'initial' && typeof preset === 'string') {
        selectedApp.value = preset;
        isCustomMode.value = false;
        if (props.addFlowSeedMcpUrl) {
          nextTick(() => {
            props.serverForm.url = props.addFlowSeedMcpUrl ?? '';
          });
        }
      } else {
        selectedApp.value = null;
        isCustomMode.value = false;
      }
    }
    if (open && props.mode === 'edit') {
      lastAutoGeneratedPrefix.value = props.serverForm.prefix.trim();
    }
  },
  { immediate: true },
);

const selectedAppData = computed(() =>
  ssoApps.find((app) => app.id === selectedApp.value) ?? null,
);

const editCatalogAppData = computed((): SsoApp | null => {
  if (props.mode !== 'edit') return null;
  const slug = props.editingServerSlug?.trim();
  if (slug) {
    const bySlug = ssoApps.find((app) => app.id === slug);
    if (bySlug) return bySlug;
  }
  const name = props.editingServerName?.trim();
  if (name) {
    const lower = name.toLowerCase();
    return ssoApps.find((app) => app.name.toLowerCase() === lower) ?? null;
  }
  return null;
});

function getFaviconUrl(domain: string) {
  return `https://www.google.com/s2/favicons?domain=${domain}&sz=64`;
}

function handleSelectCustomApp() {
  selectedApp.value = null;
  isCustomMode.value = true;
  appSelectRef.value?.hide();
}

function onNameBlur() {
  const suggested = generatePrefixFromName(props.serverForm.name);
  const current = props.serverForm.prefix.trim();
  if (!suggested) return;
  if (!current || current === lastAutoGeneratedPrefix.value) {
    props.serverForm.prefix = suggested.slice(0, 8);
    lastAutoGeneratedPrefix.value = props.serverForm.prefix;
  }
}

/** Runs on focus leaving the URL field (InputText does not forward @blur to the native input). */
function onUrlFieldFocusOut() {
  const raw = props.serverForm.url;
  const t = raw.trim();
  if (t === '') {
    urlBlurErrorMessage.value = URL_EMPTY_MSG;
    return;
  }
  if (!isValidHttpOrHttpsUrl(raw)) {
    urlBlurErrorMessage.value = URL_INVALID_MSG;
    return;
  }
  urlBlurErrorMessage.value = null;
}

watch(selectedApp, (appId) => {
  if (appId) {
    isCustomMode.value = false;
    const app = ssoApps.find((a) => a.id === appId);
    if (app) {
      props.serverForm.name = app.name;
      const suggested = generatePrefixFromName(app.name).slice(0, 8);
      props.serverForm.prefix = suggested;
      lastAutoGeneratedPrefix.value = props.serverForm.prefix;
      props.serverForm.url = '';
    }
  }
});

const isCustomFormValid = computed(() => {
  const f = props.serverForm;
  return (
    f.prefix.trim() !== '' &&
    f.name.trim() !== '' &&
    isValidHttpOrHttpsUrl(f.url)
  );
});

const isSsoFormValid = computed(() => {
  const f = props.serverForm;
  return (
    selectedApp.value !== null &&
    f.name.trim() !== '' &&
    f.prefix.trim() !== '' &&
    isValidHttpOrHttpsUrl(f.url)
  );
});

const isEditFormValid = computed(() => {
  const f = props.serverForm;
  return (
    f.prefix.trim() !== '' &&
    f.name.trim() !== '' &&
    isValidHttpOrHttpsUrl(f.url)
  );
});

const isPrimaryDisabled = computed(() => {
  if (props.mode === 'edit') return !isEditFormValid.value;
  if (!selectedAppData.value && !isCustomMode.value) return true;
  if (isCustomMode.value) return !isCustomFormValid.value;
  return !isSsoFormValid.value;
});

const AUTH_STYLES_WITH_API_DOCS_LINK = new Set(['API Token', 'API Key']);

const showApiDocsLinkField = computed(() =>
  AUTH_STYLES_WITH_API_DOCS_LINK.has(props.serverForm.authStyle),
);

watch(
  () => props.serverForm.authStyle,
  (next, prev) => {
    if (AUTH_STYLES_WITH_API_DOCS_LINK.has(prev) && !AUTH_STYLES_WITH_API_DOCS_LINK.has(next)) {
      props.serverForm.apiDocumentationUrl = '';
    }
  },
);

defineExpose({
  isPrimaryDisabled,
});
</script>

<template>
  <!-- Edit -->
  <div v-if="mode === 'edit'" class="flex flex-col gap-md">
    <template v-if="editCatalogAppData">
      <div class="flex flex-col gap-xs">
        <h3 class="text-heading-3 text-neutral-base">{{ editCatalogAppData.name }}</h3>
        <span class="text-body-md text-neutral-subtle">{{ editCatalogAppData.description }}</span>
        <a
          :href="editCatalogAppData.mcpDocsUrl"
          target="_blank"
          rel="noopener noreferrer"
          class="text-body-md-bold text-link-base hover:text-link-hover active:text-link-active"
        >
          View MCP Documentation
        </a>
      </div>
    </template>
    <FormField label="Name" :required="true">
      <template #default="{ inputId }">
        <InputText
          :id="inputId"
          v-model="serverForm.name"
          class="w-full"
          @blur="onNameBlur"
        />
      </template>
    </FormField>
    <FormField
      label="Prefix"
      :required="true"
      helpText="Prepended to MCP tool names on this server (max 8 characters)"
    >
      <template #default="{ inputId }">
        <InputText
          :id="inputId"
          v-model="serverForm.prefix"
          class="w-full"
          maxlength="8"
          placeholder="e.g. BA"
        />
      </template>
    </FormField>
    <FormField
      label="URL"
      :required="true"
      :helpText="urlBlurErrorMessage ?? undefined"
      :helpTextSeverity="urlBlurErrorMessage ? 'error' : 'default'"
    >
      <template #default="{ inputId }">
        <div class="w-full" @focusout="onUrlFieldFocusOut">
          <InputText
            :id="inputId"
            v-model="serverForm.url"
            class="w-full"
            placeholder="e.g. https://mcp.example.com/mcp"
            :invalid="!!urlBlurErrorMessage"
          />
        </div>
      </template>
    </FormField>
    <Divider />
    <div class="flex flex-col gap-sm" role="group" aria-labelledby="phase01-dialog-auth-style-edit">
      <h4 id="phase01-dialog-auth-style-edit" class="text-heading-4 text-neutral-base">
        Authentication method
      </h4>
      <div>
        <SelectButton
          v-model="serverForm.authStyle"
          :options="authStyleOptions"
          optionLabel="label"
          optionValue="value"
          :allowEmpty="false"
        />
        <p
          v-if="serverForm.authStyle === 'OAuth'"
          class="text-body-md text-neutral-base pt-3"
        >
          If your organization uses
          <a
            :href="jumpCloudSsoHref"
            target="_blank"
            rel="noopener noreferrer"
            class="text-body-md-bold text-link-base hover:text-link-hover active:text-link-active"
          >JumpCloud SSO</a>
          for this app, access is managed through the app's SSO configuration.
        </p>
        <Phase01OauthAdvancedCollapse
          v-if="serverForm.authStyle === 'OAuth'"
          v-model:collapsed="oauthAdvancedCollapsed"
          :server-form="serverForm"
          id-suffix="edit"
        />
      </div>
    </div>
    <FormField
      v-if="showApiDocsLinkField"
      label="App API documentation link"
      helpText="This link is shown in the user portal so users can open the app's API documentation and set up API keys."
    >
      <template #default="{ inputId }">
        <InputText
          :id="inputId"
          v-model="serverForm.apiDocumentationUrl"
          class="w-full"
          placeholder="https://..."
        />
      </template>
    </FormField>
  </div>

  <!-- Add -->
  <div v-else class="flex flex-col gap-md">
    <FormField label="App">
      <template #default="{ inputId }">
        <Select
          ref="appSelectRef"
          :id="inputId"
          v-model="selectedApp"
          :options="ssoApps"
          optionLabel="name"
          optionValue="id"
          placeholder="Select an app..."
          filter
          filterPlaceholder="Search apps..."
          class="w-full!"
        >
          <template #filtericon>
            <MagnifyingGlassIcon />
          </template>
          <template #option="{ option }">
            <div class="flex items-center gap-sm">
              <img
                :src="getFaviconUrl(option.domain)"
                :alt="option.name"
                class="size-5 rounded-xs"
              />
              <span class="text-body-md text-neutral-base">{{ option.name }}</span>
            </div>
          </template>
          <template #value="slotProps">
            <div v-if="slotProps.value && !isCustomMode" class="flex items-center gap-sm">
              <img
                :src="getFaviconUrl(selectedAppData?.domain ?? '')"
                :alt="selectedAppData?.name"
                class="size-5 rounded-xs"
              />
              <span class="text-body-md text-field-base">{{ selectedAppData?.name }}</span>
            </div>
            <div v-else-if="isCustomMode" class="flex items-center gap-sm">
              <CommandLineIcon class="size-5 text-neutral-subtle" />
              <span class="text-body-md text-field-base">Custom App</span>
            </div>
            <span v-else class="text-body-md text-field-placeholder">Select an app...</span>
          </template>
          <template #footer>
            <div class="p-sm border-t border-neutral-default_solid">
              <div
                class="flex items-center gap-sm px-3 py-2 rounded-sm cursor-pointer hover:bg-state-hover transition-colors"
                @click="handleSelectCustomApp"
              >
                <CommandLineIcon class="size-5 text-neutral-subtle" />
                <span class="text-body-md text-neutral-base">Custom App</span>
              </div>
            </div>
          </template>
        </Select>
      </template>
    </FormField>

    <template v-if="!selectedAppData && !isCustomMode">
      <Divider />

      <div class="flex h-auto flex-col items-center gap-sm py-10">
        <img
          :src="addServerEmptyIllustrationSrc"
          alt=""
          width="64"
          height="64"
          class="size-16 shrink-0"
        />
        <span class="text-body-md text-neutral-subtle">Select an app to get started</span>
      </div>
    </template>

    <template v-if="selectedAppData && !isCustomMode">
      <Divider />

      <div class="flex flex-col gap-xs">
        <h3 class="text-heading-3 text-neutral-base">{{ selectedAppData.name }}</h3>
        <span class="text-body-md text-neutral-subtle">{{ selectedAppData.description }}</span>
        <a
          :href="selectedAppData.mcpDocsUrl"
          target="_blank"
          rel="noopener noreferrer"
          class="text-body-md-bold text-link-base hover:text-link-hover active:text-link-active"
        >
          View MCP Documentation
        </a>
      </div>

      <FormField label="Name" :required="true">
        <template #default="{ inputId }">
          <InputText
            :id="inputId"
            v-model="serverForm.name"
            class="w-full"
            @blur="onNameBlur"
          />
        </template>
      </FormField>
      <FormField
        label="Prefix"
        :required="true"
        helpText="Prepended to MCP tool names on this server (max 8 characters)"
      >
        <template #default="{ inputId }">
          <InputText
            :id="inputId"
            v-model="serverForm.prefix"
            class="w-full"
            maxlength="8"
            placeholder="e.g. BA"
          />
        </template>
      </FormField>
      <FormField
        label="URL"
        :required="true"
        :helpText="urlBlurErrorMessage ?? undefined"
        :helpTextSeverity="urlBlurErrorMessage ? 'error' : 'default'"
      >
        <template #default="{ inputId }">
          <div class="w-full" @focusout="onUrlFieldFocusOut">
            <InputText
              :id="inputId"
              v-model="serverForm.url"
              class="w-full"
              placeholder="e.g. https://mcp.example.com/mcp"
              :invalid="!!urlBlurErrorMessage"
            />
          </div>
        </template>
      </FormField>
      <Divider />
      <div class="flex flex-col gap-sm" role="group" aria-labelledby="phase01-dialog-auth-style-sso">
        <h4 id="phase01-dialog-auth-style-sso" class="text-heading-4 text-neutral-base">
          Authentication method
        </h4>
        <div>
          <SelectButton
            v-model="serverForm.authStyle"
            :options="authStyleOptions"
            optionLabel="label"
            optionValue="value"
            :allowEmpty="false"
          />
          <p
            v-if="serverForm.authStyle === 'OAuth'"
            class="text-body-md text-neutral-base pt-3"
          >
            If your organization uses
            <a
              :href="jumpCloudSsoHref"
              target="_blank"
              rel="noopener noreferrer"
              class="text-body-md-bold text-link-base hover:text-link-hover active:text-link-active"
            >JumpCloud SSO</a>
            for this app, access is managed through the app's SSO configuration.
          </p>
          <Phase01OauthAdvancedCollapse
            v-if="serverForm.authStyle === 'OAuth'"
            v-model:collapsed="oauthAdvancedCollapsed"
            :server-form="serverForm"
            id-suffix="sso"
          />
        </div>
      </div>
      <FormField
        v-if="showApiDocsLinkField"
        label="App API documentation link"
        helpText="This link is shown in the user portal so users can open the app's API documentation and set up API keys."
      >
        <template #default="{ inputId }">
          <InputText
            :id="inputId"
            v-model="serverForm.apiDocumentationUrl"
            class="w-full"
            placeholder="https://..."
          />
        </template>
      </FormField>
    </template>

    <template v-if="isCustomMode">
      <Divider />

      <FormField label="Name" :required="true">
        <template #default="{ inputId }">
          <InputText
            :id="inputId"
            v-model="serverForm.name"
            class="w-full"
            @blur="onNameBlur"
          />
        </template>
      </FormField>
      <FormField
        label="Prefix"
        :required="true"
        helpText="Prepended to MCP tool names on this server (max 8 characters)"
      >
        <template #default="{ inputId }">
          <InputText
            :id="inputId"
            v-model="serverForm.prefix"
            class="w-full"
            maxlength="8"
            placeholder="e.g. BA"
          />
        </template>
      </FormField>
      <FormField
        label="URL"
        :required="true"
        :helpText="urlBlurErrorMessage ?? undefined"
        :helpTextSeverity="urlBlurErrorMessage ? 'error' : 'default'"
      >
        <template #default="{ inputId }">
          <div class="w-full" @focusout="onUrlFieldFocusOut">
            <InputText
              :id="inputId"
              v-model="serverForm.url"
              class="w-full"
              placeholder="e.g. https://mcp.example.com/mcp"
              :invalid="!!urlBlurErrorMessage"
            />
          </div>
        </template>
      </FormField>
      <Divider />
      <div class="flex flex-col gap-sm" role="group" aria-labelledby="phase01-dialog-auth-style-custom">
        <h4 id="phase01-dialog-auth-style-custom" class="text-heading-4 text-neutral-base">
          Authentication method
        </h4>
        <div>
          <SelectButton
            v-model="serverForm.authStyle"
            :options="authStyleOptions"
            optionLabel="label"
            optionValue="value"
            :allowEmpty="false"
          />
          <p
            v-if="serverForm.authStyle === 'OAuth'"
            class="text-body-md text-neutral-base pt-3"
          >
            If your organization uses
            <a
              :href="jumpCloudSsoHref"
              target="_blank"
              rel="noopener noreferrer"
              class="text-body-md-bold text-link-base hover:text-link-hover active:text-link-active"
            >JumpCloud SSO</a>
            for this app, access is managed through the app's SSO configuration.
          </p>
          <Phase01OauthAdvancedCollapse
            v-if="serverForm.authStyle === 'OAuth'"
            v-model:collapsed="oauthAdvancedCollapsed"
            :server-form="serverForm"
            id-suffix="custom"
          />
        </div>
      </div>
      <FormField
        v-if="showApiDocsLinkField"
        label="App API documentation link"
        helpText="This link is shown in the user portal so users can open the app's API documentation and set up API keys."
      >
        <template #default="{ inputId }">
          <InputText
            :id="inputId"
            v-model="serverForm.apiDocumentationUrl"
            class="w-full"
            placeholder="https://..."
          />
        </template>
      </FormField>
    </template>
  </div>
</template>
